### ISSUE TITLE
Allow explicit list of repos

### ISSUE THREAD

**Issue by jayvdb** [Mariocj89/gitorg#8]
An explicitly list of repos will allow a subset of an org, or repos from different orgs.

https://github.com/gitshelf/gitshelf might be a source of inspiration.

**Comment by mariocj89** [comment]
Indeed, would be quite good to have a .gitorg file in the folder to store such metadata.

If you are interested in contributing such, please let me know. Otherwise I would probably start to draft something next week

**Comment by mariocj89** [comment]
@jayvdb Thanks for the pointer, I am working on merging the idea with gitorg and totally love it. Closing it as this is feasible now (practically rewritten the whole thing).

**Comment by jayvdb** [comment]
Is anything needed in order to support using alternative remote names ; ala https://github.com/gitshelf/gitshelf/issues/3 , https://github.com/mgedmin/ghcloneall/issues/2 and https://github.com/vcstools/vcstools/issues/126 ?

**Comment by mariocj89** [comment]
It might be feasible as part of #13, just that reading from your usecase it feels it should probably go into the git project itself.
